### ISSUE TITLE
Wrong z3 in requirements

### ISSUE THREAD

**Issue by Durbatuluk1701** [CrafterKolyan/wannabe-cubes-dissection#1]
I believe you are trying to use the SMT solver [z3](https://github.com/Z3Prover/z3) for this problem, but have instead referred to [this package](https://github.com/presslabs/z3).
This pip package requirements should be `z3-solver` [link](https://pypi.org/project/z3-solver/) not `z3`

**Comment by CrafterKolyan** [comment]
Thank you, that's true, I fixed requirements.txt
